---
version: 2.1

orbs:
  prometheus-orb: simonpasquier/prometheus-orb@0.6.0

executors:
  # Whenever the Go version is updated here, .travis.yml and .promu.yml
  # should also be updated.
  golang:
    docker:
    - image: circleci/golang:1.12

jobs:
  test:
    executor: golang

    steps:
    - prometheus-orb/setup_environment
    - run:
        command: make check_license style unused lint build check_assets
        environment:
          # Run garbage collection more aggresively to avoid getting OOMed during the lint phase.
          GOGC: "20"
    - prometheus-orb/check_proto
    - prometheus-orb/store_artifact:
        file: prometheus
    - prometheus-orb/store_artifact:
        file: promtool

  makefile_sync:
    executor: golang
    steps:
    - checkout
    - run: ./scripts/sync_makefiles.sh

workflows:
  version: 2
  prometheus:
    jobs:
    - test:
        filters:
          tags:
            only: /.*/
    - prometheus-orb/build:
        name: build
        filters:
          tags:
            only: /.*/
    - prometheus-orb/publish_master:
        requires:
        - test
        - build
        filters:
          branches:
            only: master
    - prometheus-orb/publish_release:
        requires:
        - test
        - build
        filters:
          tags:
            only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
          branches:
            ignore: /.*/
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - makefile_sync
